export type InventoryCategory =
  | 'Beverages'
  | 'Snacks & Confectionery'
  | 'Ready-to-Eat'
  | 'Dairy & Frozen'
  | 'Grocery & Staples'
  | 'Health & Personal Care'
  | 'Household & Cleaning'
  | 'Tobacco & Smoking'
  | 'Electronics & Accessories'
  | 'Magazines & Stationery'
  | 'Seasonal & Novelty'
  | 'Miscellaneous';

export type InventoryStatus = 'in-stock' | 'low-stock' | 'out-of-stock';
export type TrendDirection = 'up' | 'down' | 'stable';

export interface InventoryItem {
  id: string;
  sku: string;
  name: string;
  category: InventoryCategory;
  currentStock: number;
  reorderPoint: number;
  maxStock: number;
  price: number;
  status: InventoryStatus;
  trend: TrendDirection;
  trendPercentage: number;
  lastRestocked?: Date;
  supplier?: string;
}

// Helper function to generate SKU
const generateSKU = (category: string, index: number): string => {
  const categoryCode = category
    .split(' ')[0]
    .substring(0, 3)
    .toUpperCase();
  return `${categoryCode}-${String(index).padStart(4, '0')}`;
};

// Helper function to determine stock status
const getStockStatus = (current: number, reorder: number): InventoryStatus => {
  if (current === 0) return 'out-of-stock';
  if (current <= reorder) return 'low-stock';
  return 'in-stock';
};

// Helper function to generate random trend
const generateTrend = (): { trend: TrendDirection; percentage: number } => {
  const trends: TrendDirection[] = ['up', 'down', 'stable'];
  const trend = trends[Math.floor(Math.random() * trends.length)];
  const percentage = trend === 'stable' ? 0 : Math.floor(Math.random() * 30) + 5;
  return { trend, percentage };
};

// Generate inventory items based on the items.txt data
export const inventoryItems: InventoryItem[] = [
  // Beverages
  {
    id: 'inv-001',
    sku: generateSKU('Beverages', 1),
    name: 'Coca-Cola 330ml',
    category: 'Beverages',
    currentStock: 245,
    reorderPoint: 100,
    maxStock: 500,
    price: 1.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 12,
  },
  {
    id: 'inv-002',
    sku: generateSKU('Beverages', 2),
    name: 'Bottled Water 500ml',
    category: 'Beverages',
    currentStock: 450,
    reorderPoint: 200,
    maxStock: 800,
    price: 0.8,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-003',
    sku: generateSKU('Beverages', 3),
    name: 'Red Bull Energy Drink 250ml',
    category: 'Beverages',
    currentStock: 85,
    reorderPoint: 80,
    maxStock: 300,
    price: 2.5,
    status: 'low-stock',
    trend: 'up',
    trendPercentage: 18,
  },
  {
    id: 'inv-004',
    sku: generateSKU('Beverages', 4),
    name: 'Iced Tea Lemon 500ml',
    category: 'Beverages',
    currentStock: 180,
    reorderPoint: 100,
    maxStock: 400,
    price: 1.8,
    status: 'in-stock',
    trend: 'down',
    trendPercentage: 8,
  },
  {
    id: 'inv-005',
    sku: generateSKU('Beverages', 5),
    name: 'Orange Juice 1L',
    category: 'Beverages',
    currentStock: 120,
    reorderPoint: 60,
    maxStock: 250,
    price: 3.2,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 15,
  },
  {
    id: 'inv-006',
    sku: generateSKU('Beverages', 6),
    name: 'Sprite 330ml',
    category: 'Beverages',
    currentStock: 0,
    reorderPoint: 100,
    maxStock: 500,
    price: 1.5,
    status: 'out-of-stock',
    trend: 'down',
    trendPercentage: 25,
  },
  {
    id: 'inv-007',
    sku: generateSKU('Beverages', 7),
    name: 'Starbucks Frappuccino 250ml',
    category: 'Beverages',
    currentStock: 95,
    reorderPoint: 50,
    maxStock: 200,
    price: 3.8,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 22,
  },
  {
    id: 'inv-008',
    sku: generateSKU('Beverages', 8),
    name: 'Green Tea Unsweetened 500ml',
    category: 'Beverages',
    currentStock: 145,
    reorderPoint: 80,
    maxStock: 300,
    price: 2.0,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 10,
  },

  // Snacks & Confectionery
  {
    id: 'inv-009',
    sku: generateSKU('Snacks', 9),
    name: "Lay's Potato Chips Classic 50g",
    category: 'Snacks & Confectionery',
    currentStock: 180,
    reorderPoint: 100,
    maxStock: 400,
    price: 1.2,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 14,
  },
  {
    id: 'inv-010',
    sku: generateSKU('Snacks', 10),
    name: 'KitKat Chocolate Bar 45g',
    category: 'Snacks & Confectionery',
    currentStock: 220,
    reorderPoint: 120,
    maxStock: 500,
    price: 1.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 20,
  },
  {
    id: 'inv-011',
    sku: generateSKU('Snacks', 11),
    name: 'Pringles Original 150g',
    category: 'Snacks & Confectionery',
    currentStock: 65,
    reorderPoint: 60,
    maxStock: 200,
    price: 2.8,
    status: 'low-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-012',
    sku: generateSKU('Snacks', 12),
    name: 'Doritos Nacho Cheese 75g',
    category: 'Snacks & Confectionery',
    currentStock: 155,
    reorderPoint: 80,
    maxStock: 350,
    price: 1.8,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 16,
  },
  {
    id: 'inv-013',
    sku: generateSKU('Snacks', 13),
    name: 'Snickers Bar 50g',
    category: 'Snacks & Confectionery',
    currentStock: 190,
    reorderPoint: 100,
    maxStock: 400,
    price: 1.3,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 12,
  },
  {
    id: 'inv-014',
    sku: generateSKU('Snacks', 14),
    name: 'Trail Mix Premium 100g',
    category: 'Snacks & Confectionery',
    currentStock: 45,
    reorderPoint: 50,
    maxStock: 150,
    price: 3.5,
    status: 'low-stock',
    trend: 'down',
    trendPercentage: 5,
  },
  {
    id: 'inv-015',
    sku: generateSKU('Snacks', 15),
    name: 'Gummy Bears 200g',
    category: 'Snacks & Confectionery',
    currentStock: 125,
    reorderPoint: 70,
    maxStock: 250,
    price: 2.2,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-016',
    sku: generateSKU('Snacks', 16),
    name: 'Popcorn Butter 85g',
    category: 'Snacks & Confectionery',
    currentStock: 88,
    reorderPoint: 60,
    maxStock: 200,
    price: 1.6,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 9,
  },

  // Ready-to-Eat
  {
    id: 'inv-017',
    sku: generateSKU('Ready', 17),
    name: 'Chicken Sandwich',
    category: 'Ready-to-Eat',
    currentStock: 35,
    reorderPoint: 30,
    maxStock: 80,
    price: 4.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 18,
  },
  {
    id: 'inv-018',
    sku: generateSKU('Ready', 18),
    name: 'Tuna Wrap',
    category: 'Ready-to-Eat',
    currentStock: 22,
    reorderPoint: 25,
    maxStock: 60,
    price: 4.0,
    status: 'low-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-019',
    sku: generateSKU('Ready', 19),
    name: 'Sushi Combo Box',
    category: 'Ready-to-Eat',
    currentStock: 18,
    reorderPoint: 15,
    maxStock: 40,
    price: 6.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 25,
  },
  {
    id: 'inv-020',
    sku: generateSKU('Ready', 20),
    name: 'Cup Noodles Beef',
    category: 'Ready-to-Eat',
    currentStock: 145,
    reorderPoint: 80,
    maxStock: 300,
    price: 1.8,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 14,
  },
  {
    id: 'inv-021',
    sku: generateSKU('Ready', 21),
    name: 'Hot Dog',
    category: 'Ready-to-Eat',
    currentStock: 40,
    reorderPoint: 35,
    maxStock: 90,
    price: 2.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 11,
  },
  {
    id: 'inv-022',
    sku: generateSKU('Ready', 22),
    name: 'Microwave Pasta Carbonara',
    category: 'Ready-to-Eat',
    currentStock: 65,
    reorderPoint: 40,
    maxStock: 120,
    price: 3.8,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },

  // Dairy & Frozen
  {
    id: 'inv-023',
    sku: generateSKU('Dairy', 23),
    name: 'Vanilla Ice Cream Bar',
    category: 'Dairy & Frozen',
    currentStock: 95,
    reorderPoint: 60,
    maxStock: 200,
    price: 2.0,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 20,
  },
  {
    id: 'inv-024',
    sku: generateSKU('Dairy', 24),
    name: 'Slurpee Cup',
    category: 'Dairy & Frozen',
    currentStock: 150,
    reorderPoint: 80,
    maxStock: 300,
    price: 1.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 28,
  },
  {
    id: 'inv-025',
    sku: generateSKU('Dairy', 25),
    name: 'Fresh Milk 1L',
    category: 'Dairy & Frozen',
    currentStock: 85,
    reorderPoint: 50,
    maxStock: 150,
    price: 2.8,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-026',
    sku: generateSKU('Dairy', 26),
    name: 'Greek Yogurt 150g',
    category: 'Dairy & Frozen',
    currentStock: 48,
    reorderPoint: 40,
    maxStock: 100,
    price: 1.9,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 8,
  },
  {
    id: 'inv-027',
    sku: generateSKU('Dairy', 27),
    name: 'Cheese Slices 200g',
    category: 'Dairy & Frozen',
    currentStock: 72,
    reorderPoint: 45,
    maxStock: 150,
    price: 3.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },

  // Grocery & Staples
  {
    id: 'inv-028',
    sku: generateSKU('Grocery', 28),
    name: 'White Rice 1kg',
    category: 'Grocery & Staples',
    currentStock: 55,
    reorderPoint: 40,
    maxStock: 120,
    price: 4.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-029',
    sku: generateSKU('Grocery', 29),
    name: 'Instant Ramen Pack (5)',
    category: 'Grocery & Staples',
    currentStock: 120,
    reorderPoint: 60,
    maxStock: 250,
    price: 5.0,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 12,
  },
  {
    id: 'inv-030',
    sku: generateSKU('Grocery', 30),
    name: 'Cooking Oil 1L',
    category: 'Grocery & Staples',
    currentStock: 38,
    reorderPoint: 35,
    maxStock: 80,
    price: 6.5,
    status: 'in-stock',
    trend: 'down',
    trendPercentage: 5,
  },
  {
    id: 'inv-031',
    sku: generateSKU('Grocery', 31),
    name: 'Spaghetti 500g',
    category: 'Grocery & Staples',
    currentStock: 65,
    reorderPoint: 40,
    maxStock: 120,
    price: 2.8,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-032',
    sku: generateSKU('Grocery', 32),
    name: 'Canned Tuna 185g',
    category: 'Grocery & Staples',
    currentStock: 88,
    reorderPoint: 50,
    maxStock: 180,
    price: 2.2,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },

  // Health & Personal Care
  {
    id: 'inv-033',
    sku: generateSKU('Health', 33),
    name: 'Colgate Toothpaste 100ml',
    category: 'Health & Personal Care',
    currentStock: 145,
    reorderPoint: 80,
    maxStock: 300,
    price: 3.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-034',
    sku: generateSKU('Health', 34),
    name: 'Hand Sanitizer 100ml',
    category: 'Health & Personal Care',
    currentStock: 95,
    reorderPoint: 60,
    maxStock: 200,
    price: 2.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 15,
  },
  {
    id: 'inv-035',
    sku: generateSKU('Health', 35),
    name: 'Dove Soap Bar 100g',
    category: 'Health & Personal Care',
    currentStock: 115,
    reorderPoint: 70,
    maxStock: 250,
    price: 2.0,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-036',
    sku: generateSKU('Health', 36),
    name: 'Shampoo 200ml',
    category: 'Health & Personal Care',
    currentStock: 72,
    reorderPoint: 50,
    maxStock: 150,
    price: 4.8,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-037',
    sku: generateSKU('Health', 37),
    name: 'Deodorant Spray 150ml',
    category: 'Health & Personal Care',
    currentStock: 58,
    reorderPoint: 40,
    maxStock: 120,
    price: 5.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-038',
    sku: generateSKU('Health', 38),
    name: 'Tissues Box (100 sheets)',
    category: 'Health & Personal Care',
    currentStock: 88,
    reorderPoint: 60,
    maxStock: 180,
    price: 1.8,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 8,
  },
  {
    id: 'inv-039',
    sku: generateSKU('Health', 39),
    name: 'Paracetamol 500mg (10 tablets)',
    category: 'Health & Personal Care',
    currentStock: 42,
    reorderPoint: 40,
    maxStock: 100,
    price: 3.2,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },

  // Household & Cleaning
  {
    id: 'inv-040',
    sku: generateSKU('Household', 40),
    name: 'Laundry Detergent 500ml',
    category: 'Household & Cleaning',
    currentStock: 55,
    reorderPoint: 35,
    maxStock: 100,
    price: 6.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-041',
    sku: generateSKU('Household', 41),
    name: 'Dish Soap 400ml',
    category: 'Household & Cleaning',
    currentStock: 68,
    reorderPoint: 40,
    maxStock: 120,
    price: 3.8,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-042',
    sku: generateSKU('Household', 42),
    name: 'Trash Bags (20 pack)',
    category: 'Household & Cleaning',
    currentStock: 82,
    reorderPoint: 50,
    maxStock: 150,
    price: 4.2,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-043',
    sku: generateSKU('Household', 43),
    name: 'Paper Towels (6 rolls)',
    category: 'Household & Cleaning',
    currentStock: 45,
    reorderPoint: 30,
    maxStock: 100,
    price: 5.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 6,
  },

  // Electronics & Accessories
  {
    id: 'inv-044',
    sku: generateSKU('Electronics', 44),
    name: 'USB-C Cable 1m',
    category: 'Electronics & Accessories',
    currentStock: 38,
    reorderPoint: 25,
    maxStock: 80,
    price: 8.5,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 18,
  },
  {
    id: 'inv-045',
    sku: generateSKU('Electronics', 45),
    name: 'Phone Charger 5V 2A',
    category: 'Electronics & Accessories',
    currentStock: 52,
    reorderPoint: 30,
    maxStock: 100,
    price: 12.0,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 22,
  },
  {
    id: 'inv-046',
    sku: generateSKU('Electronics', 46),
    name: 'Earphones 3.5mm',
    category: 'Electronics & Accessories',
    currentStock: 28,
    reorderPoint: 25,
    maxStock: 70,
    price: 9.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-047',
    sku: generateSKU('Electronics', 47),
    name: 'Power Bank 10000mAh',
    category: 'Electronics & Accessories',
    currentStock: 18,
    reorderPoint: 15,
    maxStock: 50,
    price: 25.0,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 15,
  },
  {
    id: 'inv-048',
    sku: generateSKU('Electronics', 48),
    name: 'AA Batteries (4 pack)',
    category: 'Electronics & Accessories',
    currentStock: 92,
    reorderPoint: 50,
    maxStock: 180,
    price: 4.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },

  // Magazines & Stationery
  {
    id: 'inv-049',
    sku: generateSKU('Magazines', 49),
    name: 'Ballpoint Pen (Blue)',
    category: 'Magazines & Stationery',
    currentStock: 145,
    reorderPoint: 80,
    maxStock: 300,
    price: 0.8,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-050',
    sku: generateSKU('Magazines', 50),
    name: 'Notebook A5',
    category: 'Magazines & Stationery',
    currentStock: 58,
    reorderPoint: 40,
    maxStock: 120,
    price: 2.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-051',
    sku: generateSKU('Magazines', 51),
    name: 'Greeting Card Birthday',
    category: 'Magazines & Stationery',
    currentStock: 72,
    reorderPoint: 50,
    maxStock: 150,
    price: 3.0,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },

  // Seasonal & Novelty
  {
    id: 'inv-052',
    sku: generateSKU('Seasonal', 52),
    name: 'Umbrella Compact',
    category: 'Seasonal & Novelty',
    currentStock: 42,
    reorderPoint: 30,
    maxStock: 100,
    price: 12.0,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 35,
  },
  {
    id: 'inv-053',
    sku: generateSKU('Seasonal', 53),
    name: '7-Eleven T-Shirt (M)',
    category: 'Seasonal & Novelty',
    currentStock: 28,
    reorderPoint: 20,
    maxStock: 60,
    price: 15.0,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },

  // Miscellaneous
  {
    id: 'inv-054',
    sku: generateSKU('Miscellaneous', 54),
    name: 'Pet Treats Dog Biscuits',
    category: 'Miscellaneous',
    currentStock: 35,
    reorderPoint: 25,
    maxStock: 80,
    price: 4.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-055',
    sku: generateSKU('Miscellaneous', 55),
    name: 'Collectible Cup Limited Edition',
    category: 'Miscellaneous',
    currentStock: 12,
    reorderPoint: 10,
    maxStock: 30,
    price: 8.0,
    status: 'in-stock',
    trend: 'up',
    trendPercentage: 45,
  },

  // Tobacco & Smoking
  {
    id: 'inv-056',
    sku: generateSKU('Tobacco', 56),
    name: 'Lighter Disposable',
    category: 'Tobacco & Smoking',
    currentStock: 185,
    reorderPoint: 100,
    maxStock: 400,
    price: 1.0,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
  {
    id: 'inv-057',
    sku: generateSKU('Tobacco', 57),
    name: 'Matches Box',
    category: 'Tobacco & Smoking',
    currentStock: 95,
    reorderPoint: 60,
    maxStock: 200,
    price: 0.5,
    status: 'in-stock',
    trend: 'stable',
    trendPercentage: 0,
  },
];

// Recalculate status based on current stock
inventoryItems.forEach((item) => {
  item.status = getStockStatus(item.currentStock, item.reorderPoint);
});
